# Generated by Django 4.2.5 on 2023-09-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mreports',
            name='FYyear',
        ),
        migrations.RemoveField(
            model_name='mreports',
            name='amt',
        ),
        migrations.RemoveField(
            model_name='mreports',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mreports',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='mreports',
            name='total',
        ),
    ]
