# Generated by Django 4.2.5 on 2023-09-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_mprodcutions_srno_mprodcutions_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mprodcutions',
            name='id',
        ),
        migrations.AddField(
            model_name='mprodcutions',
            name='srno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
