# Generated by Django 4.2.5 on 2023-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_mprodcutions_id_mprodcutions_srno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mprodcutions',
            name='srno',
        ),
        migrations.AddField(
            model_name='mprodcutions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
